apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-db-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query-db
  template:
    metadata:
      labels:
        app: query-db
    spec:
      containers:
        - name: query-db-image
          image: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: query-db-service
spec:
  selector:
    app: query-db
  ports:
    - name: query-db-port
      protocol: TCP
      port: 27017
      targetPort: 27017
